services:
    blogger_blog.twig.extension:
        class: Blogger\BlogBundle\Twig\Extensions\BloggerBlogExtension
#        arguments: [@translator]
        tags:
            - { name: twig.extension }

#    blogger_blog.example:
#        class: Blogger\BlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    blogger_blog.twig.translator:
       class: Blogger\BlogBundle\Twig\Extensions\BloggerBlogExtension
       arguments: [@translator]